### PR TITLE
Improved PDF hash handling

### PR DESCRIPTION
**Pull request by gjtorikian**
Closes https://github.com/gjtorikian/html-proofer/issues/787

### CODE REVIEW

**Comment by stevecheckoway** [comment]
Would you mind changing the tests so that they're not fetching PDFs from my website? I provided that just as an example of a link that failed because the PDF was parsed as html. I'm definitely not committing to maintaining slides for old classes I've taught at the same URL forever.

**Comment by gjtorikian** [comment]
The test suite uses VCR to record the (expensive) HTTP call once, and then simply reuses that fixture any time the test is run again: https://github.com/gjtorikian/html-proofer/blob/main/spec/html-proofer/fixtures/vcr_cassettes/links/pdf_w_hash_broken_html_log_level_error_type_file_.yml

Is that ok?

**Comment by stevecheckoway** [comment]
That contains the complete PDF. I don't own the contents of that PDF (they are lecture slides I use with permission from the author). Please use a different PDF.

**Comment by gjtorikian** [comment]
Ok in the future please provide a test case that is safe to reproduce please.

**Pull request merged**
