### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by stephengroat**
to start with #423 

i can easily make a `.rubocop.yml` file that disables errors like[ `Block too long`](https://travis-ci.org/gjtorikian/html-proofer/jobs/230567237#L261), [`Line too long`](https://travis-ci.org/gjtorikian/html-proofer/jobs/230567237#L261), etc. let me know if that would be wanted

### CODE REVIEW

**Comment by stephengroat** [comment]
I've looked through the error that I get on the [`default` rake task](https://travis-ci.org/gjtorikian/html-proofer/jobs/230567236#L554). doesn't make sense to me, has the website changed?

**Comment by gjtorikian** [comment]
Thanks for this, especially the file renames!!!

> has the website changed?

It's possible! Let me look into it.

**Comment by stephengroat** [comment]
i'll see if i can do some more cleaning and get rid of the errors that i know i caused by renaming files

**Comment by stephengroat** [comment]
did some more work on this. let me know what you think.

**Comment by gjtorikian** [comment]
Thank you very much!

I think I messed up the `git rebase` just now. Your commits are definitely on `master`, and your contributions have counted towards the project: https://github.com/gjtorikian/html-proofer/commits?author=stephengroat

But for some reason there's a merge conflict with this specific PR, and it's not reflecting as `merged`. I'm going to close this PR as stale. But again: I appreciate your contribution! Your changes are in! You have authorship credit! Just the UI here seems busted.

**Pull request closed without merging**
