### PR TITLE
Fix internal link format

### LINKED ISSUE #695: Problems with internal link cache re-checking logic (4.0.0.rc3)
Cached internal broken links are not re-checked

```bash
rm -rf example_site
mkdir -p example_site
echo '
<!doctype html>
<html>
<head><title>Example</title></head>
<body>
<a href="/missing.html">Missing internal link</a>
</body>
</html>
' > example_site/index.html
```

Running first with empty cache
```bash
rm -rf tmp/.htmlproofer
bundle exec htmlproofer example_site --log-level debug --cache '{"timeframe": "1d"}'
# [...]
# Adding /missing.html to internal cache
# Adding 1 new internal link to the cache
# Removing 0 outdated internal links from the cache
# Checking 1 internal link
# Ran on 1 file!
#
#
# For the Links > Internal check, the following failures were found:
#
# * In example_site/index.html (line 5):
#
#   internally linking to /missing.html, which does not exist
#
#
# HTML-Proofer found 1 failure!
```

Run again: the broken link is not re-checked

```bash
rm -rf tmp/.htmlproofer
bundle exec htmlproofer example_site --log-level debug --cache '{"timeframe": "1d"}'
# Found 1 internal link in the cache
# Adding 0 new internal links to the cache
# Removing 0 outdated internal links from the cache
# Checking 0 internal links
# Ran on 1 file!
#
#
# HTML-Proofer finished successfully.
```

### PR DESCRIPTION
**Pull request by gjtorikian**
Actually close #695. 

Sorry to trouble you @riccardoporreca but would you be able to validate this works as expected on your end? It seems to be working for me but I'd like to be extra sure.

### CODE REVIEW

**Comment by riccardoporreca** [comment]
@gjtorikian, sure, happy to review and validate... I will have some time over the weekend.

**Comment by riccardoporreca** [comment]
@gjtorikian, coming back to this later than I originally hoped...

It looks like your new commit 40f88376585dfb7acbebd4c6f99481ce4f254c15 includes my very basic attempt to address #695 in https://github.com/riccardoporreca/html-proofer/commit/b9a5cd1e91f90934dfe312b98672ca6b12840ca4 (which includes also log statements and explicit metadata update that we may want to still include)

This however still suffers from what described in https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008201940 and followed-up in the comments and commits further down in #695, which is the main motivation for introducing context-based keys for internal links (see mainly https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008213424)

In a sense this PR is addressing only the original PR #696 (before the accidental force-push): I have actually created a "restored" version of the original branch (which I still had locally): https://github.com/gjtorikian/html-proofer/compare/main...riccardoporreca:feature/695-fix-internal-cache-metadata-check-restored

Is the intention to go only for this part, perhaps as a first step before reconsidering https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008213424?

Let me know what is your intention, I am very keen on helping out also by creating clean branches reflecting what we want to achieve (Git is great for this).

**Comment by gjtorikian** [comment]
To be honest... I am confused. 😵‍💫 Partly because of my force Git error, but partly also because I don't understand what the error actually is.

Does https://github.com/gjtorikian/html-proofer/compare/main...riccardoporreca:feature/695-fix-internal-cache-metadata-check-restored#diff-56f6584338ed220240decc27e7186469985a760ecec8e03071a6545ff370c693 represent the minimal test case for the issue you're noticing? 

This PR was mostly meant to address the very first issue spotted in #695. Is there a test case for the issue in https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008201940 ?

**Comment by riccardoporreca** [comment]
> To be honest... I am confused. face_with_spiral_eyes Partly because of my force Git error, but partly also because I don't understand what the error actually is.

Don't worry @gjtorikian , I probably did not help :) with opening a PR and having a separate "continuation branch" https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008204282 for proposing the rethinking of internal cache keys to address the additional issue which would not be addressed by the original PR.

In any case, if you see the history of comments and commits (I tried to be very verbose with the messages) following the mention of the additional, more fundamental issue in https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008201940:

- I introduced in https://github.com/riccardoporreca/html-proofer/commit/b56343f9bf4cdf33c09a1531ed1a983a8f22b2e1 a test case `internal links > new failure for cached found url > does recheck failures, regardless of url found for other files` revealing the issue, see https://github.com/riccardoporreca/html-proofer/runs/4750865471?check_suite_focus=true#step:6:233
- The new test case was successful after the rethinking of the internal cache key I implemented, see https://github.com/riccardoporreca/html-proofer/runs/4750972114?check_suite_focus=true#step:6:333 (there were however new failures since I did not want to update the other tests to reflect the new cache keys before getting your opinion on the approch, see the last comments in https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008436722.
- The summary of the changes on top of the original PR (which would also apply to this PR) were mentioned in  https://github.com/gjtorikian/html-proofer/issues/695#issuecomment-1008213424, where however the "net" comparison is now visible for the `-restored` branch at https://github.com/riccardoporreca/html-proofer/compare/feature/695-fix-internal-cache-metadata-check-restored...riccardoporreca:feature/695-investigate-internal-cache-key-metadata

Given this, why don't we proceed as follows?

1. Let's first get this PR merged w/o considering the additional issue and the rethinking of the cache.
    - Here I would only propose to re-include the `if not found` part of my original commit https://github.com/riccardoporreca/html-proofer/commit/b9a5cd1e91f90934dfe312b98672ca6b12840ca4 (besides the useful debug log, I believe the comments there still apply)
    - A minor "cosmetic" feedback on this PR is about the replacement of arrows with `:`, where i noticed many double- spaces like `:  ` in the README, not sure if that is intentional, e.g.
      https://github.com/gjtorikian/html-proofer/blob/bfa74164a6e68fd139bba3db8235ae29eb5cc634/README.md?plain=1#L101
2. I can then create a clean branch a PR for the additional issue and the internal cache key re-thinking, where we can (re)discuss the topic more in detail, unless as of now you believe it is not a direction you would consider.

Of course, feel free to go down any route you believe more sensible.

**Comment by gjtorikian** [comment]
> * A minor "cosmetic" feedback on this PR is about the replacement of arrows with `:`, where i noticed many double- spaces like `:  ` in the README, not sure if that is intentional, e.g.

Thanks! Just a sloppy find-replace. 

> 2\. I can then create a clean branch a PR for the additional issue and the internal cache key re-thinking, where we can (re)discuss the topic more in detail, unless as of now you believe it is not a direction you would consider.

This makes sense to me. Thank you for your help.

**Comment by riccardoporreca** [comment]
@gjtorikian, I have created a clean issue #702 for the open problem, will try later this week to consolidate a new clean PR for the fix as discussed

**Pull request merged**
