### PR TITLE
Replace null chars with empty ones

### PR DESCRIPTION
**Pull request by ilyalyo**
issue #409

### CODE REVIEW

**Comment by gjtorikian** [comment]
Could you add a test for this as well, please?

**Comment by ilyalyo** [comment]
updated

**Comment by fulldecent** [comment]
Looks good, I am +1 to merge

**Comment by gjtorikian** [comment]
The test doesn't appear to be doing anything. I checked this branch out, and then reverted the one-line change made:

``` diff
diff --git a/lib/html-proofer/url_validator.rb b/lib/html-proofer/url_validator.rb
index 672e783..c54d010 100644
--- a/lib/html-proofer/url_validator.rb
+++ b/lib/html-proofer/url_validator.rb
@@ -175,7 +175,7 @@ module HTMLProofer
       return false unless @options[:check_external_hash]
       return false unless (hash = hash?(href))
 
-      body_doc = create_nokogiri(response.body.gsub("\u0000", ''))
+      body_doc = create_nokogiri(response.body)
 
       # user-content is a special addition by GitHub.
       xpath = %(//*[@name="#{hash}"]|//*[@id="#{hash}"])
```

The test provided still passes, which means that the line change as no effect on the test whatsoever.

That's because the file provided doesn't actually have a `null` byte in it. I had to go back and fetch [this file](https://github.com/gjtorikian/html-proofer/issues/409#issuecomment-303633639) before the test demonstrated a pass/fail.

**Pull request merged**
