### PR TITLE
Ensure Access-Control-Allow-Origin: * when check sri

### PR DESCRIPTION
**Pull request by ilyalyo**
issue #417

### CODE REVIEW

**Comment by Hanzei** [comment]
What is the status of this PR?

**Comment by hanzei** [comment]
Ping @gjtorikian

**Comment by gjtorikian** [comment]
This PR will need tests. It seems that fixture files were added, but no tests for them.

**Comment by hanzei** [comment]
@ilyalyo Could you please add some test to your changes?

**Pull request closed without merging**
