### PR TITLE
Implement Open Graph

### LINKED ISSUE #111: Support Open Graph
The [Open Graph](http://ogp.me/) protocol requires two properties for every page we could check:

* `og:image` - An image URL which should represent your object within the graph.
* `og:url` - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

Example:

```html
<meta property="og:url" content="http://www.example.com/" />
<meta property="og:image" content="http://www.example.com/image.png" />
```

### PR DESCRIPTION
**Pull request by peternewman**
This should close #111. Based on @penibelst 's work in #182 and #282 .

### CODE REVIEW

**Comment by peternewman** [comment]
I just need to address https://github.com/gjtorikian/html-proofer/pull/282#r48315197 .

**Comment by peternewman** [comment]
Working now, I still need to address https://github.com/gjtorikian/html-proofer/pull/282#r48315197 and any other comments.

**Comment by peternewman** [comment]
Missing tests added.

**Comment by peternewman** [comment]
I think this is ready for review now @gjtorkian .

The failing test just seems to be failing on your Travis, it just worked fine on mine for the same commit (possibly a timeout):
https://travis-ci.org/peternewman/html-proofer/#L275

**Comment by gjtorikian** [comment]
Wow, this looks absolutely perfect. 😍 

> The failing test just seems to be failing on your Travis, it just worked fine on mine for the same commit (possibly a timeout):

Indeed, I can't reproduce it. I'm going to go ahead and merge anyway. Thank you!

**Comment by peternewman** [comment]
I can't take most of the credit, I just tweaked @penibelst 's work to deal with the refactoring in html-proofer and added a few more tests.

Indeed the merge ran fine:
https://travis-ci.org/gjtorikian/html-proofer/builds/165935428

I normally just re-run Travis when I hit those issues, but couldn't on yours, I guess as I don't have admin rights on your repo.

**Pull request merged**
