### PR TITLE
Create a test for urlencoded file name

### PR DESCRIPTION
**Pull request by penibelst**
This is a starting point for fixing #143. I cannot implement the fix.

### CODE REVIEW

**Comment by parkr** [comment]
I think we `CGI.escape` the filenames, so if you `CGI.unescape` them, you'd get the proper filename and could then read?

**Comment by penibelst** [comment]
@parkr Thank you for the hint. It works.

@gjtorikian The sorting by path test fails on machine:

```
  1) HTML::Proofer#options sorting understands sorting by path
     Failure/Error: expect(output.strip).to eq("""
       
       expected: "- spec/html/proofer/fixtures/sorting/path/multiple_issues.html\n  *  tel: contains no phone number\n  *  internal image gpl.png does not exist\n  *  image gpl.png does not have an alt attribute\n- spec/html/proofer/fixtures/sorting/path/single_issue.html\n  *  image has a terrible filename (./Screen Shot 2012-08-09 at 7.51.18 AM.png)"
            got: "- spec/html/proofer/fixtures/sorting/path/multiple_issues.html\n  *  internal image gpl.png does not exist\n  *  image gpl.png does not have an alt attribute\n  *  tel: contains no phone number\n- spec/html/proofer/fixtures/sorting/path/single_issue.html\n  *  image has a terrible filename (./Screen Shot 2012-08-09 at 7.51.18 AM.png)"
       
       (compared using ==)
       
       Diff:
       
       @@ -1,7 +1,7 @@
        - spec/html/proofer/fixtures/sorting/path/multiple_issues.html
       -  *  tel: contains no phone number
          *  internal image gpl.png does not exist
          *  image gpl.png does not have an alt attribute
       +  *  tel: contains no phone number
        - spec/html/proofer/fixtures/sorting/path/single_issue.html
          *  image has a terrible filename (./Screen Shot 2012-08-09 at 7.51.18 AM.png)
```

The paths are sorted, but the nested messages have another order. The test is disabled on Travis (comment: “would love to know why Travis barfs here”). Should the error be ignored?

**Comment by gjtorikian** [comment]
> The paths are sorted, but the nested messages have another order.

Are you on a Linux machine, by any chance?

**Comment by penibelst** [comment]
> Are you on a Linux machine, by any chance?

Yes, Ubuntu 14.10

**Comment by gjtorikian** [comment]
> The paths are sorted, but the nested messages have another order. 

Looks like https://github.com/gjtorikian/html-proofer/commit/f8dd45db0b6e62042bc9cd2893b3709ad124e6ee in the refactor will finally address this.

**Comment by penibelst** [comment]
I agree.

**Pull request merged**
