### PR TITLE
correct --ignore option

### LINKED ISSUE #185: invalid option: --ignore
in  [README] it mentions the option ` --ignore`
> htmlproof ./out --swap wow:cow,mow:doh --ext .html.erb --ignore www.github.com

But when I run it , I get
> htmlproof 2.1.0 | Error:  Whoops, we can't understand your command.
> htmlproof 2.1.0 | Error:  invalid option: --ignore
> htmlproof 2.1.0 | Error:  Run your command again with the --help switch to see available options.

### PR DESCRIPTION
**Pull request by eksperimental**
fixes #185

### CODE REVIEW

**Comment by penibelst** [comment]
@eksperimental Thank you. Could you please fix the `--swap` option too? It must be `--href-swap`.

**Comment by penibelst** [comment]
> Could you please fix the --swap option too?

Oh, I see this PR is not extendable. I will fix it myself.

**Comment by eksperimental** [comment]
done. check if the comment to "href_swap" is correct, or you prefer "href-swap"

**Comment by eksperimental** [comment]
@penibelst by the way, what is the proper way to ignore all the pages under a certain directory.
i' m using `--file--ignore ./_site/docs/` and it is not working, 
thanks

**Comment by penibelst** [comment]
Look in #177

**Comment by eksperimental** [comment]
cool. i didn' t know it shold be absolute path relative to the root folder. thanks

**Pull request merged**
